# Generated by Django 5.2.7 on 2025-11-13 19:21

import events.models
import events.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=events.models.event_photo_upload_to, validators=[events.validators.validate_photo_image]),
        ),
    ]
