# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='couple_names',
            field=models.CharField(blank=True, help_text="E.g., 'John & Jane', 'The Smiths', or any format", max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='bg_color_1',
            field=models.CharField(blank=True, help_text='Background gradient color 1 (hex code, e.g., #ffe6f7)', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='bg_color_2',
            field=models.CharField(blank=True, help_text='Background gradient color 2 (hex code, e.g., #d3f4ff)', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='bg_color_3',
            field=models.CharField(blank=True, help_text='Background gradient color 3 (hex code, e.g., #ffe7d2)', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Primary color for text (hex code, e.g., #2b2d42)', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='accent_color_1',
            field=models.CharField(blank=True, help_text='Accent gradient color 1 (hex code, e.g., #7f5cff)', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='accent_color_2',
            field=models.CharField(blank=True, help_text='Accent gradient color 2 (hex code, e.g., #ff89b3)', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='text_primary_color',
            field=models.CharField(blank=True, help_text='Primary text color (hex code, e.g., #2b2d42)', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='text_muted_color',
            field=models.CharField(blank=True, help_text='Muted text color (hex code, e.g., #6c7286)', max_length=7),
        ),
    ]
