# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_event_personalization_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='upload_page_subtitle',
            field=models.TextField(blank=True, help_text="Subtitle message displayed on the upload page (e.g., 'Ossz meg egy különleges pillanatot az ifjú párral.')"),
        ),
    ]
